/*
    --------------------------------------------------------------------------------
        Revelation-AD-edit  -  modified derivative of "Revelation"
        Upstream: https://github.com/HaringPro/Revelation  (C) 2026 HaringPro

        This file is an addition made for this derivative.
        Copyright 2026 AnotherCream

        Licensed under the Apache License, Version 2.0. See NOTICE at repo root.
    --------------------------------------------------------------------------------
*/

#define IRC_COMPUTE
layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(32, 32, 1);

#define gl_FragCoord (vec4(gl_GlobalInvocationID.xy, 0.0, 1.0))
#define main voxelGI_fragment_main
#include "/program/gi/VoxelGI.frag"
#undef main
#undef gl_FragCoord

void main() {
    voxelGI_fragment_main();
}
